INSERT INTO ARTICLES (id, title, category, date, content)
VALUES ('48a95af7-8b83-4a08-8001-0f865db8ea26', 'What is Lorem Ipsum?', 'Fun facts', '2021-11-15',
        'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.'),
       ('15a95af7-8b83-4a08-8001-0f865db8ea27', 'Where does Lorem Ipsum come from?', 'Fun facts', '2021-11-15',
        'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32. The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.'),
       ('ebdee4f9-5763-4afc-85ed-98b2fdefb35f', 'Why do we use Lorem Ipsum?', 'Fun facts', '2021-11-15',
        'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).'),
       ('abdee4f9-5763-4afc-85ed-98b2fdefb35d', 'Where can I get some of Lorem Ipsum?', 'Fun facts', '2021-11-18',
        'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isnt anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.'),
       ('58a95af7-8b83-4a08-8001-0f865db8ea26', 'The World of Tomorrow', 'Environmental protection', '2021-11-20',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque rhoncus aliquam nisl, finibus ultrices nisl. Nullam imperdiet risus a tortor tempor lacinia. Donec ultricies purus et nunc luctus, nec imperdiet purus scelerisque. Curabitur in maximus sapien. Etiam a sapien convallis, euismod nibh at, aliquet nunc. Pellentesque aliquet rhoncus mauris, a sagittis quam luctus eu. Vivamus semper vehicula risus, a mattis ante varius in. Proin imperdiet nulla id urna pharetra, ultrices luctus tortor convallis. Etiam ornare leo nibh, ut pellentesque mi eleifend eget. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin consectetur, leo quis hendrerit sollicitudin, nunc enim dictum turpis, et placerat mi dui at nisl. Cras non dolor vitae nisi sagittis pharetra a id dui. Suspendisse vel nisl aliquam purus feugiat porttitor ut et tellus. Etiam sed orci nec arcu ullamcorper dignissim sit amet quis leo. Fusce ac placerat enim. Duis sem lorem, efficitur non interdum vel, efficitur sit amet elit. Quisque convallis a est non condimentum. Nunc finibus arcu nec sem auctor, ac luctus velit tristique. Integer non turpis tempus, consectetur sapien sit amet, porttitor nunc. Vivamus vitae ultricies ligula. Sed ac ex purus. Nunc at dignissim magna, porta eleifend neque. Proin tincidunt semper ante at porta. Nullam sed tempus ex.'),
       ('45a95af7-8b83-4a08-8001-0f865db8ea27', 'Endangered species of India', 'Wildlife', '2021-11-23', 'Nullam consectetur ullamcorper quam, non maximus ante. Proin pellentesque metus id tellus ultricies consequat. Nam malesuada a tellus vel maximus. Quisque vel metus nec lorem mattis volutpat. Sed laoreet nunc mauris, sed tempus ante egestas a. Pellentesque augue quam, placerat ac faucibus vitae, posuere sed quam. Vestibulum ut quam turpis. Vestibulum tincidunt enim in lacus tincidunt, accumsan iaculis dolor aliquam. Donec eros massa, volutpat et venenatis non, facilisis luctus mi. Duis eleifend, massa nec porta tristique, ante leo lacinia ex, a vehicula lacus mauris quis nulla. Proin congue massa nec elit posuere, placerat accumsan nunc faucibus. Sed condimentum velit vel auctor gravida. Quisque vulputate tortor ut diam posuere elementum. Quisque viverra quam vel metus mattis, in ornare leo vestibulum. In in viverra libero, vel molestie tortor. Nullam tempor odio ac nisi ultricies, hendrerit placerat massa sagittis. Quisque nec suscipit dui. Duis in tempor augue. Duis a accumsan diam. Quisque venenatis commodo elit, et laoreet quam dignissim non. Donec in sagittis nisi, in ultrices ipsum. Donec rutrum, purus vehicula cursus ultricies, libero lacus bibendum urna, sit amet scelerisque felis augue sit amet velit. Aliquam pharetra aliquet maximus. Nam accumsan iaculis auctor. Praesent et sapien nunc. Cras nisi ex, vehicula viverra purus nec, pretium bibendum nibh. Cras pharetra elementum nunc a convallis. Aliquam at urna id orci tristique euismod. In id orci vehicula erat suscipit vehicula. Aliquam erat volutpat. Aliquam bibendum ipsum ac arcu lacinia auctor. Nulla in porta tortor, non tempus dolor. Ut imperdiet purus ut sapien eleifend dignissim. Maecenas at lacus non dolor tempus laoreet non dictum libero. Fusce vel justo et erat congue vehicula non vitae leo. Pellentesque aliquam justo in augue lobortis pulvinar. Sed ultrices ullamcorper aliquam. Vestibulum erat erat, venenatis a placerat eget, ultricies ac erat.'),
       ('abdee4f9-5763-4afc-85ed-98b2fdefb35f', 'Timebomb in the Atlantics', 'Environmental protection', '2021-11-24', 'Suspendisse hendrerit mollis nulla, sit amet fermentum justo rhoncus non. Maecenas sodales arcu nec semper blandit. Vestibulum sodales velit lorem, sit amet pharetra mauris fermentum sodales. Nam at hendrerit est. Quisque eu congue sapien. Donec et viverra est, id consectetur risus. Etiam commodo vel leo ut varius. Aliquam tristique maximus nunc, sed feugiat purus bibendum at. Sed blandit, massa eget iaculis venenatis, nulla turpis tempor arcu, sed efficitur elit metus non enim. Aenean efficitur metus vitae pharetra posuere. In at dolor libero. Mauris a ultrices magna. Mauris et orci fringilla, interdum tortor ut, luctus nisl. Nullam pharetra massa quis lorem consectetur, et facilisis nunc varius. Nunc vitae lacus eget massa congue tristique. Suspendisse eget euismod lacus. Phasellus sit amet iaculis arcu, quis finibus nisl. Nunc nec urna hendrerit, iaculis nisl eu, rutrum turpis. Donec vehicula, nibh commodo facilisis sollicitudin, ligula nibh mollis purus, in tristique enim ex nec nisi. Praesent risus mi, posuere ac hendrerit a, vestibulum sed enim. Ut pellentesque elit arcu, vel placerat orci accumsan quis. Vivamus nec lacinia eros. Maecenas finibus mattis libero, in consectetur urna convallis a. Proin ac posuere nibh. Maecenas ultrices mattis lorem, ut luctus nulla pretium et. Nulla eu tempor ligula. Nunc ut vulputate lectus, eu finibus ex. Nunc mollis neque quis gravida imperdiet. Nunc eget vestibulum neque.'),
       ('cbdee4f9-5763-4afc-85ed-98b2fdefb35d', 'Australias most dangerous', 'Wildlife', '2021-11-26', 'Integer convallis non orci sit amet feugiat. Nulla in eros sit amet metus blandit ultricies. Nunc ultrices est vel viverra consectetur. Pellentesque nisi enim, vehicula vel purus ac, dapibus interdum elit. Nam diam dui, feugiat a cursus tristique, tempor nec magna. Praesent sodales mauris id aliquam imperdiet. Nulla a elementum massa. Suspendisse rutrum ante convallis, rhoncus diam in, tincidunt lacus. Suspendisse ac tempor neque, nec consequat justo.Maecenas et tempor ex. Sed a est ut massa pharetra consequat. Integer commodo massa eget orci vulputate euismod. Nullam dictum egestas porta. Nullam lobortis ultrices ligula, non mollis nisi facilisis eu. Praesent semper, nisl ut maximus viverra, quam lorem sagittis urna, vitae venenatis augue ipsum ut est. Pellentesque finibus justo ut augue varius condimentum. Nam finibus, felis nec venenatis pulvinar, mi turpis congue nunc, vitae dapibus est dolor sit amet ex. Nulla elementum lobortis molestie. Nunc cursus consectetur nisl, vitae tempor elit. Curabitur pharetra felis at odio lobortis, ut lacinia lorem pellentesque. Suspendisse accumsan ex quis lorem viverra, vel cursus tellus semper. Donec sagittis ac dui at sagittis. Nunc vestibulum egestas urna quis interdum. Donec in magna ac quam scelerisque sodales. In dapibus facilisis ante eu ultricies. Vestibulum vel dolor non nunc lacinia mattis. Sed sodales sed ex vitae eleifend. Proin sit amet luctus felis. Etiam rhoncus commodo tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus.');

INSERT INTO USERS (id, username, email, password)
VALUES ('c2aa5f20-2441-40f8-8cce-d31dbd17bc84', 'user', 'user@blog.com', '{bcrypt}$2a$10$jYIbAef1H7S.womsk7MRtOCSEx/DgM7CZ1nNeLLzoZ/OPs0a25DV2'),
       ('bd8968db-ad2a-4dd0-a0ab-7eebcc05427e', 'admin', 'admin@blog.com', '{bcrypt}$2a$10$VylYhXDaKC7W28tQTvYYkOdZIj2pnPVIobXOConbXy3xeBcF6Xuni');

INSERT INTO ROLES(id, name)
VALUES ('60dbb7bb-99a0-42eb-a837-8be6b697c074', 'USER'),
    ('3906c549-44bf-494b-9537-5e1658a029a8', 'ADMIN');

INSERT INTO USERS_ROLES (user_id, roles_id) VALUES
    ('c2aa5f20-2441-40f8-8cce-d31dbd17bc84', '60dbb7bb-99a0-42eb-a837-8be6b697c074'),
    ('bd8968db-ad2a-4dd0-a0ab-7eebcc05427e', '60dbb7bb-99a0-42eb-a837-8be6b697c074'),
    ('bd8968db-ad2a-4dd0-a0ab-7eebcc05427e', '3906c549-44bf-494b-9537-5e1658a029a8');

